### ISSUE TITLE
Script to obtain the values in Figure 3

### ISSUE THREAD

**Issue by ratishsp** [jxiw/BiGS#2]
Hi, 
Congratulations for the nice work and thanks for sharing the code!
Figure 3 in the paper was not very clear to me. Especially "values indicate absolute value of contribution of each relative position (-10, . . ., 10) cropped from the full 2 × 128."
Could you please share the script you used to compute these values?

![image](https://github.com/jxiw/BiGS/assets/3006607/7bf7d80a-c47f-4a11-857b-8d8faab3371b)

**Comment by jxiw** [comment]
Hello, 
Thanks for open this issuse. My collaborate will post it soon!

**Comment by NathanYanJing** [comment]
Hello,

As we have two SSMs, forward and backward, we took the forward positions on the left side, and backward on the right side.  0 to be the starting positions for both. 

Assume you store all kernel values in f and b. Then, in particular,  we used the min-max function and absolute values to preprocess values. 

`min_max(np.abs(np.concatenate([np.flip(f[layer],0), b[layer]])))
`

We then convert this into a data frame df for visualization purposes. We have modified the source code ridge_plot to get the shape that we wanted. But you can refer to 

```
def ridge_plot(df, colormap, overlap, u, l, x_tick_list, y_tick_list, figsize, file, linecolor, linestyle):
    x_range = []
    for index in range(u, l, 1):
        x_range.append(index)
    
#     plt.axvline(x=128, color="black", zorder=15)
    fig, axes = joyplot(df, 
                        kind="values", 
                        x_range=x_range, 
                        figsize=figsize,  
                        linecolor=linecolor, 
                        color=colormap, 
                        linewidth=1.5,
                        linestyle=linestyle,
                        overlap=overlap)

    
    axes[-1].xaxis.set_ticks_position('top')
    axes[-1].set_xticks(x_range)
    axes[-1].set_xticklabels(x_tick_list)
    axes[-1].set_yticklabels(y_tick_list)
    axes[-1].tick_params(axis='both', which='major', labelsize=10)
    axes[-1].tick_params(axis='both', which='major', labelsize=10)
    
    plt.rc('axes', labelsize=10)    # fontsize of the x and y labels
    plt.rc('legend', fontsize=10)    # legend fontsize
    plt.rcParams['figure.dpi'] = 500
    plt.rcParams['font.size'] = 15
    plt.subplots_adjust(left=0.1, right=0.9, top=0.9, bottom=0.1)
    plt.show()
    
    
    fig.savefig(f'results_{file}.png',transparent=True)  




```

**Comment by NathanYanJing** [comment]
If you have further questions, please feel free to email jy858@cornell.edu for prompt reply. Sorry that I didn't turn on the notifications.

**Comment by ratishsp** [comment]
Thanks, this  helps!

**Comment by ratishsp** [comment]
One minor related question. Considering that the left SSM is for forward direction and the right one for backward, shouldn't the text read as "Figure shows these values in the form of the forward and backward kernels. These kernels correspond partially to local aggregations such as the **previous** word (layer 1) or a **following** trigram (layer 6)"? 
![image](https://github.com/jxiw/BiGS/assets/3006607/4361535f-adbd-43a0-95f4-d96486e7b628)

**Comment by jxiw** [comment]
Thanks for this question. Yes, you are correct! We will change that in our next version.
